backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "artists"
    label: "Artists"
    folder: "src/pages/artists"
    create: true
    slug: "{{slug}}"
    identifier_field: name
    fields: 
      - { label: "Template Key", name: "templateKey", widget: "hidden", default: "artist-page"}
      - { label: "Name", name: "name", widget: string, }
      - { label: "About", name: "about", widget: "markdown" }
      - { label: "Profile Image", name: "profileImage", widget: image, }
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - {label: Label, name: label, widget: string}
          - {label: Url, name: url, widget: string}
          - {label: Icon, name: icon, widget: string}
  - name: "releases"
    label: "Releases"
    folder: "src/pages/releases"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Artist", name: "artist", widget: "relation", collection: "artists", searchFields: ["name"], valueField: "name",  displayFields: ["name", "soundCloudUrl"]}
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "release-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Release Date", name: "date", widget: "datetime"}
      - {label: Image, name: image, widget: image, required: false}
      - {label: Track List, name: trackList, widget: list, required: false }
      - {label: Preview HTML/embed code, name: previewHTML, widget: "text", required: false}
      - {label: "Description", name: "description", widget: "markdown", required: false }
      - {label: "Type", name: "releaseType",  widget: "select",  options: [{ label: "Release", value: "release" }, { label: "Mix", value: "mix" }, { label: "Freebie", value: "freebie" },]}
      - {label: "Soundcloud url (for site player)", name: "soundCloudUrl", widget: string, required: false }
      - label: "Links"
        name: "links"
        widget: "list"
        required: false
        fields:
          - {label: Label, name: label, widget: string}
          - {label: Url, name: url, widget: string}
          - {label: Icon, name: icon, widget: string}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/home/index.md"
        label: "Home"
        name: "home"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/contact/index.md"
        label: "Contact"
        name: "contact"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "contact-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: Links, name: links, widget: object, fields: [{label: Label, name: label, widget: string}, {label: Url, name: url, widget: string}, {label: Icon, name: icon, widget: string},]}