export { default as PrevIcon } from './baseline-fast_rewind-24px.svg'
export { default as NextIcon } from './baseline-fast_forward-24px.svg'
export { default as StopIcon } from './baseline-stop-24px.svg'
export { default as PlayIcon } from './baseline-play_circle_outline-24px.svg'
export { default as PauseIcon } from './baseline-pause_circle_outline-24px.svg'
export { default as CloseIcon } from './baseline-close-24px.svg'
export { default as AlbumIcon } from './baseline-album-24px.svg'
